In [3]:
import numpy as np


In [18]:
a = np.array([5,6.3,7],dtype='int16')
print(a)

[5 6 7]


In [6]:
b = np.array([[2.0,.0,6.0],[8.0,2.0,9.0]])
print(b)

[[2. 0. 6.]
 [8. 2. 9.]]


In [9]:

#dimensions
a.ndim
    

1

In [11]:
#shape
b.shape

(2, 3)

In [15]:
#type
a.dtype


dtype('float64')

In [17]:
b.itemsize


8

In [19]:
a.nbytes

6