In [1]:
import numpy as np


In [2]:
a = np.array([[10,21,22,2,8,9,12],[12,1,4,2,9,6,5]])
print(a)

[[10 21 22  2  8  9 12]
 [12  1  4  2  9  6  5]]


In [3]:
#get specific elements 
#0th row 3rd index
a[0,3]

2

In [4]:
a[1,4]

9

In [6]:
a[0,-2 ]

9

In [8]:
#specific row
print(a[0])

[10 21 22  2  8  9 12]


In [9]:
print(a[0,:])

[10 21 22  2  8  9 12]


In [10]:
print(a[:,0])

[10 12]


In [11]:
a[0,2]=12

In [12]:
print(a)

[[10 21 12  2  8  9 12]
 [12  1  4  2  9  6  5]]
