In [1]:
# Create a python list

a = ["0", 1, "two", "3", 4]

In [2]:
# Print each element

print("a[0]:", a[0])
print("a[1]:", a[1])
print("a[2]:", a[2])
print("a[3]:", a[3])
print("a[4]:", a[4])

a[0]: 0
a[1]: 1
a[2]: two
a[3]: 3
a[4]: 4


In [3]:
# import numpy library

import numpy as np 

In [4]:
# Create a numpy array

a = np.array([0, 1, 2, 3, 4])
a

array([0, 1, 2, 3, 4])

In [5]:
# Print each element

print("a[0]:", a[0])
print("a[1]:", a[1])
print("a[2]:", a[2])
print("a[3]:", a[3])
print("a[4]:", a[4])

a[0]: 0
a[1]: 1
a[2]: 2
a[3]: 3
a[4]: 4


In [6]:
print(np.__version__)

1.21.5


In [7]:
# Check the type of the array

type(a)

numpy.ndarray

In [8]:
# Check the type of the values stored in numpy array

a.dtype

dtype('int64')

In [9]:
b = np.array([3.1, 11.02, 6.2, 213.2, 5.2])

# Enter your code here


In [10]:
# Create numpy array

c = np.array([20, 1, 2, 3, 4])
c

array([20,  1,  2,  3,  4])

In [11]:
# Assign the first element to 100

c[0] = 100
c

array([100,   1,   2,   3,   4])

In [12]:
# Assign the 5th element to 0

c[4] = 0
c

array([100,   1,   2,   3,   0])