In [4]:
import numpy as np

a = np.array([0, 1])
b = np.array([1, 0])

dot_product = np.dot(a, b)
print(dot_product)


0


In [7]:
import numpy as np

a = np.array([[1, 0],
              [0, 1]])

b = np.array([[0, 1],
              [1, 0]])

z = a + b
print(z)


[[1 1]
 [1 1]]


In [8]:
import numpy as np

a = np.array([[1, 0,1],
              [2,2,2]])

out = a[0,1:3]
out


array([0, 1])

In [9]:
import numpy as np

a = np.array([[1, 0],
              [0, 1]])

b = np.array([[2,1],
              [1, 2]])

z = np.dot(a,b)
print(z)

[[2 1]
 [1 2]]


In [10]:
with open(example,"r") as file1:

IndentationError: expected an indented block (1975123533.py, line 1)